apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog
spec:
  selector:
    matchLabels:
      app: datadog
  template:
    metadata:
      labels:
        app: datadog
    spec:
      containers:
        - name: datadog
          image: httpd
          ports:
          - containerPort: 80