commonLabels:
  environment: prod

resources:
- ../../base/cluster
- ../../clusters/prod-cluster-lon
- ../../clusters/prod-cluster-ny

patches:
- target:
    kind: RepoSync
    name: repo-sync
  patch: |-
    - op: replace
      path: /spec/git/branch
      value: prod

