apiVersion: v1
kind: Namespace
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: tenant-a
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: tenant-b
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: tenant-admin
  namespace: tenant-a
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: tenant-admin
  namespace: tenant-b
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    change: default
    geo: uk
  name: tenant-admin-rolebinding
  namespace: tenant-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tenant-a-admin@mydomain.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    change: default
    geo: uk
  name: tenant-admin-rolebinding
  namespace: tenant-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tenant-b-admin@mydomain.com
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: repo-sync
  namespace: tenant-a
spec:
  git:
    auth: none
    branch: prod
    repo: https://github.com/ejmadkins/acm-multi-repo-tenant-a.git
  sourceFormat: unstructured
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: repo-sync
  namespace: tenant-b
spec:
  git:
    auth: none
    branch: prod
    repo: https://github.com/ejmadkins/acm-multi-repo-tenant-b.git
  sourceFormat: unstructured
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  name: ns-must-have-geo
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
  parameters:
    labels:
    - key: geo
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: default-deny-ingress
  namespace: tenant-a
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    geo: uk
  name: default-deny-ingress
  namespace: tenant-b
spec:
  podSelector: {}
  policyTypes:
  - Ingress
