apiVersion: v1
kind: Namespace
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: pre-prod-cluster-tenant-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: pre-prod-cluster-tenant-admin
  namespace: tenant-a
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    change: default
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: pre-prod-cluster-tenant-admin-rolebinding
  namespace: tenant-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pre-prod-cluster-tenant-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tenant-a-admin@mydomain.com
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    environment: pre-prod
  name: datadog
spec:
  selector:
    matchLabels:
      app: datadog
      environment: pre-prod
  template:
    metadata:
      labels:
        app: datadog
        environment: pre-prod
    spec:
      containers:
      - image: httpd
        name: datadog
        ports:
        - containerPort: 80
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  labels:
    environment: pre-prod
  name: ns-must-have-geo
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
  parameters:
    labels:
    - key: geo
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: pre-prod-cluster-default-deny-ingress
  namespace: tenant-a
spec:
  podSelector: {}
  policyTypes:
  - Ingress
