apiVersion: v1
kind: Namespace
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    cluster: pre-prod-cluster
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: tenant-a
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    cluster: pre-prod-cluster
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: tenant-admin
  namespace: tenant-a
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    change: default
    cluster: pre-prod-cluster
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: tenant-admin-rolebinding
  namespace: tenant-a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tenant-a-admin@mydomain.com
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    cluster: pre-prod-cluster
    environment: pre-prod
  name: datadog
spec:
  selector:
    matchLabels:
      app: datadog
      cluster: pre-prod-cluster
      environment: pre-prod
  template:
    metadata:
      annotations:
        configsync.gke.io/cluster-name-selector: pre-prod-cluster
      labels:
        app: datadog
        cluster: pre-prod-cluster
        environment: pre-prod
    spec:
      containers:
      - image: httpd
        name: datadog
        ports:
        - containerPort: 80
---
apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    cluster: pre-prod-cluster
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: repo-sync
  namespace: tenant-a
spec:
  git:
    auth: none
    branch: pre-prod
    repo: https://github.com/ejmadkins/acm-multi-repo-tenant-a.git
  sourceFormat: unstructured
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    cluster: pre-prod-cluster
    environment: pre-prod
  name: ns-must-have-geo
spec:
  match:
    kinds:
    - apiGroups:
      - ""
      kinds:
      - Namespace
  parameters:
    labels:
    - key: geo
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: pre-prod-cluster
  labels:
    cluster: pre-prod-cluster
    environment: pre-prod
    geo: uk
    tenant: tenant-a
  name: default-deny-ingress
  namespace: tenant-a
spec:
  podSelector: {}
  policyTypes:
  - Ingress
