apiVersion: configsync.gke.io/v1beta1
kind: RepoSync
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: dev-cluster
  labels:
    cluster: dev-cluster
    environment: dev
    geo: uk
    tenant: tenant-a
  name: dev-cluster-repo-sync
  namespace: tenant-a
spec:
  git:
    auth: none
    branch: dev
    repo: https://github.com/ejmadkins/acm-multi-repo-tenant-a.git
  sourceFormat: unstructured
