apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: dev-cluster
  labels:
    cluster: dev-cluster
    environment: dev
    geo: uk
    tenant: tenant-a
  name: dev-cluster-tenant-admin
  namespace: tenant-a
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - '*'
