apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    configsync.gke.io/cluster-name-selector: prod-cluster-ny
  labels:
    change: default
    cluster: prod-cluster-ny
    environment: prod
    tenant: tenant-b
  name: prod-ny-tenant-admin-rolebinding
  namespace: tenant-b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-ny-tenant-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: tenant-b-admin@mydomain.com
