commonLabels:
  environment: dev

resources:
- ../../base/cluster
- ../../clusters/dev-cluster

patches:
- target:
    kind: RepoSync
    name: repo-sync
  patch: |-
    - op: replace
      path: /spec/git/branch
      value: dev
