resources:
- ../../../base/cluster
- ../../../tenants/tenant-a
- ../../../tenants/tenant-b

commonAnnotations:
  configsync.gke.io/cluster-name-selector: dev-cluster

patches:
- target:
    kind: RepoSync
    name: repo-sync
  patch: |-
    - op: replace
      path: /spec/git/branch
      value: dev