namePrefix: cluster-

resources:
- ../../base/cluster
- ../../tenants/tenant-a

commonLabels:
  cluster: pre-prod-cluster

commonAnnotations:
  configsync.gke.io/cluster-name-selector: pre-prod-cluster