resources:
- ../../../base/cluster
- ../../../tenants/tenant-a

commonAnnotations:
  configsync.gke.io/cluster-name-selector: prod-cluster-lon

patches:
- target:
    kind: RepoSync
    name: repo-sync
  patch: |-
    - op: replace
      path: /spec/git/branch
      value: prod